site_name: MedNotes
site_url: https://jzpero.github.io/mdnotes/
theme:
  name: material
  icon:
    logo: material/pill
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      prebuild_index: true
  - callouts
  
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  
